apiversion: apps/v1
kind: Deployment
metadata:
  labels:
    app: online-shop-blue
  name: online-shop-blue
  namespace: online-shop

spec:
  replicas: 4 
  selector:
    matchLabels:
      app: online-shop-blue
  template:
    metadata:
      labels:
        app: online-shop-blue
    spec:
      containers:
        - image: online-shop:latest
          name: online-shop-blue
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

---
apiversion: v1
kind: Service
metadata:
  name: online-shop-blue-service
  namespace: online-shop
spec:
  selector: 
    app: online-shop-blue  
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      NodePort: 30001
