apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: online-shop-green
  name: online-shop-green
  namespace: online-shop
spec:
  replicas: 4
  selector:
    matchLabels:
      app: online-shop-green
  template:
    metadata:
      labels:
        app: online-shop-green
    spec:
      containers:
      - image: emon110852/online-shop:latest
        name: online-shop-green
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: online-shop-green-deployment-service
  namespace: online-shop
spec:
  selector:
    app: online-shop-green
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
